import "@/app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import i18nConfig, { Locale } from "@/next-i18next.config";
import { dir } from "i18next";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: {
    lang?: Locale;
  };
}) {
  return (
    <ClerkProvider>
      <html
        lang={params.lang ? params.lang : i18nConfig.defaultLocale}
        dir={params.lang ? dir(params.lang) : dir(i18nConfig.defaultLocale)}
        suppressHydrationWarning
      >
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
