
import type { Metadata } from "next";

// import { ClerkProvider } from "@clerk/nextjs";

import i18nConfig from "@/next-i18next.config";
// import { dir } from "i18next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export async function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ lang: locale }));
}

export default function AuthLayout({
  children,
}: // params,
{
  children: React.ReactNode;
  // params: {
  //   lang: Locale;
  // };
}) {
  return (
    // <ClerkProvider>
    //   <html
    //     lang={i18nConfig.defaultLocale}
    //     dir={dir(i18nConfig.defaultLocale)}
    //     suppressHydrationWarning
    //   >
    //     <body className={inter.className}>
    <div className="h-full flex items-center justify-center">{children}</div>
    //     </body>
    //   </html>
    // </ClerkProvider>
  );
}
